name: herd
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  swipeable_stack: ^0.4.3 
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  flutter_secure_storage: ^8.0.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: ^1.16.0  
  flutter_native_splash: ^2.0.0
  flutter_launcher_icons: ^0.10.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.6.1
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  logging: ^1.2.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/herd.png" # Path to your app logo
  adaptive_icon_background: "#ffffff" # (Optional) Background color for Android adaptive icon


flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/lang/
    - assets/images/totoro.png
    - assets/images/grumpy.png
    - assets/images/godzilla.png
    - assets/images/cornelius.png
    - assets/logo/herd.png
    - assets/icons/google_logo.png

flutter_native_splash:
  color: "#ffffff" # Background color
  image: assets/logo/herd.png # Path to your logo
  android: true
  ios: true
  fullscreen: true # Optional, makes splash screen cover the full screen

