name: herd
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # firebase_core: ^2.4.1
  # firebase_auth: ^4.2.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  flutter_card_swiper: ^2.0.4
  font_awesome_flutter: ^10.4.0
  # cloud_firestore: ^4.6.1
  google_fonts: ^4.0.4
  flutter_secure_storage: ^8.0.0
  intl: ^0.19.0
  flutter_localizations:   # Add this line for localization support
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/lang/   # Add this line to include localization files
