name: herd
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  swipeable_stack: ^0.4.3 # Use the latest version
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  flutter_secure_storage: ^8.0.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.6.1
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  logging: ^1.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/lang/
    - assets/images/totoro.png
    - assets/images/grumpy.png
    - assets/images/godzilla.png
