import 'user.dart';
import 'event.dart';
import 'group.dart';

List<User> getDummyUsers() {
  return [
    User(
      userId: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      profilePictureUrl: 'assets/images/godzilla.png',
      pictures: ['assets/images/godzilla.png', 'assets/images/godzilla.png'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      bio: 'A software developer with a love for coffee and books.',
      location: 'New York, USA',
      phoneNumber: '123-456-7890',
      preferences: {'theme': 'dark'},
      interests: ['coding', 'reading', 'gaming'],
      deviceId: 'device_id_123',
      deviceType: 'android',
      eventIds: [1, 2],
      groupIds: [1],
    ),
    User(
      userId: 2,
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      profilePictureUrl: 'assets/images/totoro.png',
      pictures: ['assets/images/totoro.png', 'assets/images/totoro.png'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      bio: 'A creative writer and painter.',
      location: 'San Francisco, USA',
      phoneNumber: '987-654-3210',
      preferences: {'theme': 'light'},
      interests: ['writing', 'painting', 'yoga'],
      deviceId: 'device_id_124',
      deviceType: 'ios',
      eventIds: [3, 4],
      groupIds: [2],
    ),
    User(
      userId: 3,
      name: 'Alice Johnson',
      email: 'alice.johnson@example.com',
      profilePictureUrl: 'assets/images/grumpy.png',
      pictures: ['assets/images/grumpy.png', 'assets/images/grumpy.png'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      bio: 'An avid traveler and photographer.',
      location: 'Los Angeles, USA',
      phoneNumber: '555-666-7777',
      preferences: {'theme': 'dark'},
      interests: ['traveling', 'photography', 'hiking'],
      deviceId: 'device_id_125',
      deviceType: 'android',
      eventIds: [5, 6],
      groupIds: [3],
    ),
    User(
      userId: 4,
      name: 'Bob Williams',
      email: 'bob.williams@example.com',
      profilePictureUrl: 'assets/images/godzilla.png',
      pictures: ['assets/images/godzilla.png', 'assets/images/godzilla.png'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      bio: 'A fitness enthusiast and personal trainer.',
      location: 'Chicago, USA',
      phoneNumber: '888-999-0000',
      preferences: {'theme': 'light'},
      interests: ['fitness', 'nutrition', 'running'],
      deviceId: 'device_id_126',
      deviceType: 'ios',
      eventIds: [7, 8],
      groupIds: [4],
    ),
    User(
      userId: 5,
      name: 'Carol Davis',
      email: 'carol.davis@example.com',
      profilePictureUrl: 'assets/images/totoro.png',
      pictures: ['assets/images/totoro.png', 'assets/images/totoro.png'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      bio: 'A passionate chef and food blogger.',
      location: 'Houston, USA',
      phoneNumber: '111-222-3333',
      preferences: {'theme': 'dark'},
      interests: ['cooking', 'baking', 'blogging'],
      deviceId: 'device_id_127',
      deviceType: 'android',
      eventIds: [9, 10],
      groupIds: [5],
    ),
  ];
}

List<Event> getDummyEvents() {
  return [
    Event(
      eventId: 1,
      name: 'Flutter Workshop',
      date: DateTime.now().add(Duration(days: 7)),
      location: 'Online',
      description: 'An online workshop on Flutter development.',
      userId: 1,
    ),
    Event(
      eventId: 2,
      name: 'Yoga Class',
      date: DateTime.now().add(Duration(days: 14)),
      location: 'Community Center',
      description: 'A relaxing yoga session.',
      userId: 1,
    ),
    Event(
      eventId: 3,
      name: 'Photography 101',
      date: DateTime.now().add(Duration(days: 5)),
      location: 'City Park',
      description: 'A basic course on photography.',
      userId: 2,
    ),
    Event(
      eventId: 4,
      name: 'Painting Exhibition',
      date: DateTime.now().add(Duration(days: 10)),
      location: 'Art Gallery',
      description: 'An exhibition of modern paintings.',
      userId: 2,
    ),
    Event(
      eventId: 5,
      name: 'Travel Meetup',
      date: DateTime.now().add(Duration(days: 20)),
      location: 'Beach Resort',
      description: 'Meetup for travel enthusiasts.',
      userId: 3,
    ),
    Event(
      eventId: 6,
      name: 'Hiking Adventure',
      date: DateTime.now().add(Duration(days: 15)),
      location: 'Mountain Trail',
      description: 'A hiking adventure in the mountains.',
      userId: 3,
    ),
    Event(
      eventId: 7,
      name: 'Fitness Bootcamp',
      date: DateTime.now().add(Duration(days: 2)),
      location: 'Local Gym',
      description: 'A high-intensity fitness bootcamp.',
      userId: 4,
    ),
    Event(
      eventId: 8,
      name: 'Nutrition Seminar',
      date: DateTime.now().add(Duration(days: 8)),
      location: 'Health Center',
      description: 'A seminar on healthy eating and nutrition.',
      userId: 4,
    ),
    Event(
      eventId: 9,
      name: 'Cooking Class',
      date: DateTime.now().add(Duration(days: 3)),
      location: 'Community Kitchen',
      description: 'Learn to cook delicious meals.',
      userId: 5,
    ),
    Event(
      eventId: 10,
      name: 'Baking Workshop',
      date: DateTime.now().add(Duration(days: 12)),
      location: 'Baking School',
      description: 'A workshop on baking cakes and pastries.',
      userId: 5,
    ),
  ];
}

List<Group> getDummyGroups() {
  return [
    Group(
      groupId: 1,
      name: 'Book Club',
      description: 'A group for book enthusiasts.',
      userId: 1,
    ),
    Group(
      groupId: 2,
      name: 'Tech Talks',
      description: 'A group for tech enthusiasts.',
      userId: 2,
    ),
    Group(
      groupId: 3,
      name: 'Travel Group',
      description: 'A group for travel enthusiasts.',
      userId: 3,
    ),
    Group(
      groupId: 4,
      name: 'Fitness Fanatics',
      description: 'A group for fitness enthusiasts.',
      userId: 4,
    ),
    Group(
      groupId: 5,
      name: 'Food Lovers',
      description: 'A group for people who love cooking and baking.',
      userId: 5,
    ),
  ];
}
